[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d88598c597387fd644db6f98e319c062f0b8bbd8"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "847396e8a90281a71ef841451543ef39328341d6dc0f1166aeb4b8bbb4ceb807"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.aarch64-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bf7dfdaefc9131fbc2e4e55381c8c7065420e52"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "6fb93b503686930da2255a1ab4668300adbfcc1b7711787f28124b69dadb5f2f"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fa67e802e2aa11924bf7bf35eb60fecd304661c"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "12005f00394aabdfda7def59cb23c32838eee37ac0d15700d87a4ca82b9c6d5e"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.aarch64-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfb67b29cdae8b218711af65219af88c9f536838"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "8f3f3474efd82830a3afd99b896ae4efb10cda6aba80b067d4403bad5f3aa5a2"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a76d5a503ace621ec0643d14530ca657c4fe410"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "7b532f4517f4439466141fb66179970c16c4ffe66a03ffa9c83c67ea70934acb"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06db4391f3ca3b602573e6a26652562e166c6ce0"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "c07b310785772f97c627409e5983dcfc122639e04e09d345c695bef12772cfe3"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d7ba7b4b86c36f3cc3ad1fb7b02dfe71f09f28d"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "189aac6b45663993d3379ad50f168dc8ee0fc9d9f7d37c2e940ebc90fe5b667a"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a6e151a2db7facb54181b8ca06302ea4c97d88e"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "4e39e813514bd73977a16289f8ed793045cd0d82eb379005c19874fba0ee4cfc"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2d8d0eb1aeeb1082d9f253864d1142cee07e9c6"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "4443c167996a2d5513e50c5bc006db7774dded749e4e65e97cadba0e1b4d646d"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09b1924008708d27ede8dabfec98c71179c6884a"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "274969df566923042ee28b2a5ef3441941360f705b116363cfaeab3e4bf2a01c"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dde424c2c7793fa527cf1d33f89416a7d6534a88"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "2d03a061793bad846e2693464d9ecfb630e5e3b00510d04c1b43fcca624e91a9"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a0af6c789695fb6476eaa377822382e78108881"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "e83518dd9528be437d8ebfeb87daa21612912679e9a0f8c9a5818fb82aaeea42"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b81097a5236af5bb807ff41276337e8e8b0acc1"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "c3d88aff7882a6c035990a2e41bdab425287c7a3ff7d48d49c2bdc3b37d72628"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.i686-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1fa84fde2ec2ecd0f3a5e1fe32bf6b3e99d5126"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "0c7077929b8ede9a73ceab031c242020f039c98d7aebcd762aa142d75431dd92"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.i686-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce072df78d98b3a8555dd8002611c76295290335"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "245948fae8eabc8f22da126a2bb628ba25a744cf15aa4c56bbd30ffe836a9d97"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.i686-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16264a07b6cce5fa7eaecfa8f3a756f387d7638f"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "b56bad8bdec258d4cc956f0916f4938cb7b4de19f9eefd0f737e90af37213dbd"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.i686-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc1bf2656eabe81c4b89b729b5d51bcde2cb0f90"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "57c374272d50cf68085d8e495357dca80a8e08f591e6932644cca344108b432c"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.i686-w64-mingw32-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "273570c53e9a59394c55f3a12e25f10d6bb5462f"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "77bc441a46052a6b815c4a9b8efeba41cf84dbfa099df9541664e49e5d15e4e3"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cd0dd2d8e370fc687729b24239d1c53eb672893"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "d9b03c064b813507421c2fcb0d2efb14a8c75f212af1eb751140ae8e391a8d02"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bb12e3608f9e5befbfa27f72e5737ecfc9a8633"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "14d64df82684776aa5da308b27e39af7f4fab7ef124632645bb5d1ec1ed4011f"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f073727fe715e7f1775bce80b02f64fc912b4a7"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "fff8f3356cdcbab3415ef11d03037c674a70de2951e3beadd3b50d1ebfdb159b"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.x86_64-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6478b7b1bab7a526cfc0c76582ec39a7747afd3"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "56b01a00127b7d374ff1975818eac1b09610243ba6abd06e9517e9eb487db4c8"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27668f612ae340484c64d3df2c062003cc99645b"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "f2e2c2a64dd7b11e0d17c9c498e0b5389a470341dbde506b06a994d4e57f335a"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.x86_64-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "677d9260d5d36ce4585f4c248ef6dfe6d63a5639"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "32acd23a5fd58c6e481bce0f58c79a9d5d810d601f8124472fcfd0ad84be0afb"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ede420b02ee36242d84e80c54f47c2ca4decade2"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "fdb6a66bdc886569939e67dae1d1f42e04ae61d4f90fe9364d874fe8a12233ce"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7a6beadee8cd80666f64747e7629ab5c38e1ec6"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "01e5c3f8cc28926864fe909ffddabea5c8d81d8f02af8f3db56e8f3150ada728"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.2+0/DynarePreprocessor.v6.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
