[[DynarePreprocessor]]
arch = "aarch64"
git-tree-sha1 = "8355ce3c4b2cf37e3d4faa125a8b72223545a328"
os = "macos"

    [[DynarePreprocessor.download]]
    sha256 = "aeda24902dc1fd92b9660ba0127b22cb50647bcea92ae3370df15e96c3199d36"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.aarch64-apple-darwin.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe3feb61f82c807e570548ef1b49123b32fa3f7e"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "f551b078df6b8de683486901289b9a326924a9fe922a17729a201c63becc1e80"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fd84607c6933f8dd6f9dd68d9d52000ca27f7fe"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "23d22d8fcb649bc1e78238f86e989e540203134a7de99cba740f61cb231b8b4d"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "748673cf688b09df37c031c7a54d7d20a48899e8"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "64e7f5500ecf137bb8df68b2c88720ef526449fa2c5e1dcafdacfff19e8a104a"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c98cc151d923f6f43c53c62afb8a519e223b454"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "424fd8dfd8ccdb1612bd68d2575d42513c029509a19c0f470133f01c486f8a5e"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "940f0430bc68ce7fea1e7c6ed1735c78847c1aa6"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "507070e27447552e0dda0b6e412550a31128ee767790307d157f625261493528"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d1b9bcb729e1a735ba4ebce681fa773a70c8310"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "7faae5f4fd2a2b491a295adfc363cd3940cb0ffb4a6ec2fc14f8d5ab7d2c07f8"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02a49c4fb2486e9abbb30bbab4077f00e1bc2e0e"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "9694fe16d3e0be9503383487ef4e53d63696a0360187e4a8f38d8c0ba551d1ff"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a7cd47870764ce530cf4d7bf225d503d7439b62"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "0a46acccb6a9a41e70c590d37ac91366a31bb04b540b9a9783fb16353f326696"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e3900cd2f9001eb24733dc6a5424fc450763295"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "43a3cfcf7dc4fa991c81482bfb2f3dd7947c741466a379fe795c7b83d5c13915"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ae414ad0e6c73a9bd98b03178f4c7043f73c0ec"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "348d34618d7ae4a35eae98738e660d37a5cf17f2bda1a4b151cb08dedd8c659e"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0aa98010b6a61ba064cbe34ebbf01f6da9ccf07"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "cc04c01a2518c5f346581562cb42119eca462781011b2a3ce5358de5b4266a26"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dd2854a0c937e4d5779609d8a31cac2f453f8b5"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "049b718670c87cb4864a6337378d8e68ffd97ddba0891435d1af3ef15eb767e3"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72f32dd1d183412364fdcb65e9457913773b7260"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "e5a99ea4204f97b35b92130a7a48062f3943c37b468eae26c05e46598b8cb26f"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.i686-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aba96e00f802d0bd3736b7e1533c418c794e9973"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "75bc727947cf10435236dff2d055fa89166f36e0ae3b47335496953a0720d7cc"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.i686-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68c6d6437b032f84074485ba0ed479ecd0b4f7eb"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "04bdd80375611b0ae75c31d7eda9f7460617760dc590eec1dd33dcd26eaf0a47"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.i686-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7a8c23c1dfce1071fcf46a41a298c217e6afbf5"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "98380020370a81182ea96be1029e5ed1504ccd1b7ac2e087de78fbc98d9923ca"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.i686-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8fad1167569486fd409b9a947b550678632a1eb"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "5dbac55e90172dd95cd4d5877dd3ee0db9e413d6b4e14e8486c78ba2c8931bd3"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c938602d83ec8172522c01b9f45b594c1539ffc"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "cdbd98246c3010de4f2fde052a51157bc3f0e0bcc8d8271d5a312a9d026c64ec"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35e8be7d3479739b2e5cd22079573f716822cffb"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "a52100e63a387d34e15baf9a97fbc818170cb79d68eca4dd72e4b939a2adc0e4"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67b12c151d74cdfdd2a9af9ee29c83892db818aa"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "b9709127ad0ed42ceb77b744c34b371abb691f61b7f5dac25815c28ae02caed9"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
git-tree-sha1 = "b35ea904411938e167646c5be864f3acd227ae44"
os = "macos"

    [[DynarePreprocessor.download]]
    sha256 = "c625c6d50a21dbecfcc244917df2c63a9a7725b1e1562cd7acf85456dc09f9b7"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-apple-darwin.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28ceb5123458755282158ae79b34f79cc5781d8b"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "6479465fd98608d1aee972eef83032d5dd639c4b97062c5f83f68626f3fcf730"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e8fbb485765aebf6224d5a91a37a52ad048cd13"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "716f17d869f88303ad9a1d4c1a0a299af8894bc647485f6e94feef0e012fe602"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f504789377d14cb21ebb38c6306f562d98da8f1"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "a8a900fac0059b4c60161b48720cdb93fe7e58c6354736f4a3765b8acd8afa60"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e44864fedc7926f6a56b8a421fa4af43fd7f4011"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "8505cd27181c9887ce980368e511ae26acecc35a3c07a485b2b327c6c792306e"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
git-tree-sha1 = "f53203b8abbf1a09df75e2f83a5404044e28fb3b"
os = "freebsd"

    [[DynarePreprocessor.download]]
    sha256 = "9a7c2460825dfdbb18d3afde42d7e7079462dd9bb1a3af7e5d156ec6ffaced51"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-unknown-freebsd.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eee2995aa10683c7c35aa51b3835165c5a74ef0d"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "86be9483271b1b32b101a51d132899495b6f4ac1768720f82f1bd301a19e5778"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbdaa403b92ba7e4652a3032c8e3dad7d5071a98"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "13bb35f8fb16f7b19b9c2178388e72ef440455891d0cb8b1b94fbdd7d66dbe67"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.3.0+0/DynarePreprocessor.v6.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
