[[DynarePreprocessor]]
arch = "aarch64"
git-tree-sha1 = "493ccdadb0dc155647d851ab4583cc6a84f1b082"
os = "macos"

    [[DynarePreprocessor.download]]
    sha256 = "25a57abef0d010b39bdc87290cb223a8bf68b2608d0a012b4cd1a3b1390c8798"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.aarch64-apple-darwin.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21e6e773975e243d05eb1656d2f07fce48b72c14"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "f3a8b9457b88e37448ce593e4cfdf719f2e3d7c128f350988838ff611e9a9df3"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2559554bc97eb57f7c3c726ba3e2a9ab86e2dabe"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "89cdc17ad595e82db43c606e0e563132b5e0764079b1c7c8cac24f48373355a0"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df8c62a391d0b31dc94ae083bf904185e24b4d18"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "8ff8ae1149270e1aa4e4ef667968257df1a4b944bfa071cfd8f81ef4ff107b2f"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a3333c370ac61067cbc4fa2cb090eb58f79ee38"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "a921ba3f52f181d08acad69705977b1a30dc2fc8d1476178b145ab0e2a35e028"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12a6c192a1e2fb3c56a6ec2ce11a06ad314a645b"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "029a014d5097aca789e7c205bf27b73939ddd1ff49bb28848e52d1731cdcd031"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37d2cde6a77596b522f711530e48d242b79a9325"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "741e244683094b127292208167d5dfc364d39b77ba3e9dadf56ead650a5fbe9e"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29eb6b03a1556771954e3c1cba24fce1643aae5b"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "12928f9965da8f9ce0bcbcddda791803732d2a30e8b576fb17c2a58b37de1793"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "399bbe9590b4e4d674494ea99909632536ce9dc1"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "8c27cac8f0f19a17555bd80151b6f5caafc1e9846addf08a206c5060065a0316"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6149db0b108655874e8d078425c5b0359e97d63e"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "227332521d43f48d28f7f1904f4effa655040be33962ec4d315b337e1929dafb"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b7c41a2745f04ba48379f5b833e9210b5f4801d"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "d9b9ed14980bbc767adf1a6d40d41fd2b41d39c219667f70db5f47f1f9b11014"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c9047487d2ecbc46b09dcad0223cb99b2c0a104"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "0750b4002c370800354c8dd44fc61bd3925189ba7a13b4895c35af35640125f6"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6753944463569509b146950d76ee771b04dc2a7f"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "d54be0e963817111339cf26d9ea7bb61790e1458df955a11e1ac7fed5318afea"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0e1dc2dfc7fc51a1e8c2509c43e881d4d688ff9"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "c50f338d337d3f2373cf15fee832f94abfacde1a802bd0847612c90a53dba081"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.i686-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc9bdbe0e2c057ed73110f3492e4ffc4831346a9"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "a2b0292339b896445f3c31ec279165a285e9180276675a96b44e947eacf3654c"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e76f1032a9e755a333004035aafa7e1c525e1b1"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "7eb6d1da06a90f62a4fd6ebc3f53351ef343e99913fabb2c01f91a78f628f8ac"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.i686-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b855987b7d8834592c953d0a71ea3510cbe018d4"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "f6a0406a1ed2aa9b4c166c483da934ea277a4a2745e2c8f957bab7603b271549"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "004f29fa60dcb4b43e76abf638f9a43914979eb3"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "739f52240bbdf7e0ac62806c7c3f6b885e68fce3737969a6e08785fcfced310e"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e04359beaade60f7bdf8706f4bdceb0d8f2bd24b"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "e8c9223b739f3e8c71e3600079eb849a6f9c7286c76c8c6ebc4def48ae670192"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "644351a6d62c645312ca50d9a5515c13d568d333"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "4f3ce0bfce6fc578f00889556863f470942b5df5f8c0fba77ecfcdbd4d5d1113"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5eaad471b429d68ebcd59482b8fd616a9877d75"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "e42e6161d78c3375f2292554dedcf9ce1157fcff1191cb2f4d6e39f40cc4d40d"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
git-tree-sha1 = "71dad2a02f76a21775083a3f45224f92120f531c"
os = "macos"

    [[DynarePreprocessor.download]]
    sha256 = "e83dfe39396563826a37b0b9eab71bff4a04c3f009c2925d464e5f0bf215076f"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-apple-darwin.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7fff9c119709c5fa9eb2ed135b4c1086065fc6f"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "b6adccfd49afc8224465a1be8bdb2c8c6c28ee753b758e9108565d2d35c95413"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d59ca25a4c32d521fbaf681ccaa1dd6bc7c317ef"
libc = "glibc"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "96834c644a24d7eaa14cb33b1dff65dac373aa471248c99de919a0c28d34f998"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a150a572c437d2a78a9a97407f2d780cfd94cd9c"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "deb3fbbba77cfb05c32609c468672cb1ccbf2f61b8c24005a058046e4f9f6e26"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa952c81caad0c95f41756f818eb926889db01c3"
libc = "musl"
os = "linux"

    [[DynarePreprocessor.download]]
    sha256 = "8336f06ef016c5dedcdc4bfa5163073ab8923da6eda047b7d81293971e0a55e8"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
git-tree-sha1 = "65b2ebfe424f8b2938154ec20024f807e7d11b93"
os = "freebsd"

    [[DynarePreprocessor.download]]
    sha256 = "2594eb5836e62a31599b1ee9ba7767ffa700a60d1b764c057a63d23c9293ef92"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-unknown-freebsd.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eac559c75adc3a72590115fa42f041132df00e14"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "174b036f28ba63172c2bdff74f1350bf62ac7ed29da6cb0f3a9ab218fd1ce0d5"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[DynarePreprocessor]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3421e9acc39106574ae44d584a69f697e268f139"
os = "windows"

    [[DynarePreprocessor.download]]
    sha256 = "99ee3a98a3e3f43c785d9f80e83fe0991fd62582e9a40a79a9fb6191c73fe900"
    url = "https://github.com/JuliaBinaryWrappers/DynarePreprocessor_jll.jl/releases/download/DynarePreprocessor-v6.0.0+0/DynarePreprocessor.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
